import './globals.css';

export const metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en" className="h-full">
         <body className="bg-blue-950 p-4 h-full">{children}</body>
      </html>
   );
}
